# Site settings -----------------------------------
title: Anne LechÃªne
email: clairezuliani@gmail.com
description: My own jekyll starter
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
# url: "https://clairezed.github.io" # the base hostname & protocol for your site
url: "https://anne-lechene.netlify.com" # the base hostname & protocol for your site


# Social settings ------------------------------------
github_username: clairezed
twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
  - _headers

# Jekyll assets
assets:
  precompile: [
    default-picture.png
  ]